# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD



# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# FFFFFFFFFFFFFFF
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD

if __name__ == '__main__':
    
    pass
    
    # module execution model
    # module execution model
    # module execution model
        
    # FFFFFFFFFFFFFFF
    # FFFFFFFFFFFFFFF
    # FFFFFFFFFFFFFFF
        
    
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE