# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD



# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD

if __name__ == '__main__':
    
    # module execution model
    # module execution model
    # module execution model
    
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE