# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD

# New Lines Feature
#-----------------------------------------
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 


# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# FFFFFFFFFFFFFFF
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD


# ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
# ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
# ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
# ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
# ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ

if __name__ == '__main__':
    
    pass
    
    # module execution model
    # module execution model
    # module execution model
        
    # FFFFFFFFFFFFFFF
    # FFFFFFFFFFFFFFF
    
    # ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
    # ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
    # ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
    # ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
    # ZZZZZZZZZZZZZ ZZ ZZZZZZZZZZZZ  ZZZZZZZZZZZZ ZZZZ
    
    # FFFFFFFFFFFFFFF
        
    
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    # EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE