# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD

# FFFFFFFFFFFFFFFFFF
# FFFFFFFFFFFFFFFFFF
# FFFFFFFFFFFFFFFFFF


# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# FFFFFFFFFFFFFFFFFF
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD

# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD



# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
