# New Lines Feature
#-----------------------------------------
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 


# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD

# FFFFFFFFFFFFFFFFFF
# FFFFFFFFFFFFFFFFFF
# FFFFFFFFFFFFFFFFFF

# New Lines Feature
#-----------------------------------------
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 


# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# FFFFFFFFFFFFFFFFFF
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD

# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD



# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
