# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDDDDDDDDDDD

# New Lines Feature
#-----------------------------------------
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 

# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 
# NEW LINES NEW LINES NEW LINES NEW LINES NEW LINES 


# Feature 1 augmentation
# EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
# EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
# EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG



# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD

# DDDDDDDDDDDDDDD
# DDDDDDDDDDDDDDD

# EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

# EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE